INSERT INTO master_data (id, category, name, code, sort_order, is_active) VALUES
  (UUID(), 'products', 'Basmati Rice', '1006.30', 1, TRUE),
  (UUID(), 'products', 'Mango (Chaunsa)', '0804.50', 2, TRUE),
  (UUID(), 'products', 'Mango (Sindhri)', '0804.50', 3, TRUE),
  (UUID(), 'products', 'Kinnow', '0805.10', 4, TRUE),
  (UUID(), 'products', 'Dates (Aseel)', '0804.10', 5, TRUE),
  (UUID(), 'products', 'Sesame Seeds', '1207.40', 6, TRUE),
  (UUID(), 'products', 'Maize', '1005.90', 7, TRUE),
  (UUID(), 'products', 'Potatoes', '0701.90', 8, TRUE),
  (UUID(), 'products', 'Onions', '0703.10', 9, TRUE),
  (UUID(), 'products', 'Beef Meat', '0201.30', 10, TRUE),
  (UUID(), 'products', 'Seafood (Shrimp)', '0306.17', 11, TRUE),
  (UUID(), 'products', 'Olive Oil', '1509.10', 12, TRUE),
  (UUID(), 'products', 'Citrus Fruits', '0805.90', 13, TRUE),
  (UUID(), 'products', 'Red Chili', '0904.11', 14, TRUE),
  (UUID(), 'products', 'Cotton', '5201.00', 15, TRUE),
  (UUID(), 'countries', 'China', NULL, 1, TRUE),
  (UUID(), 'countries', 'United Arab Emirates', NULL, 2, TRUE),
  (UUID(), 'countries', 'Saudi Arabia', NULL, 3, TRUE),
  (UUID(), 'countries', 'United Kingdom', NULL, 4, TRUE),
  (UUID(), 'countries', 'Malaysia', NULL, 5, TRUE),
  (UUID(), 'countries', 'Indonesia', NULL, 6, TRUE),
  (UUID(), 'countries', 'Qatar', NULL, 7, TRUE),
  (UUID(), 'countries', 'Oman', NULL, 8, TRUE),
  (UUID(), 'countries', 'Germany', NULL, 9, TRUE),
  (UUID(), 'countries', 'Kazakhstan', NULL, 10, TRUE),
  (UUID(), 'countries', 'Afghanistan', NULL, 11, TRUE),
  (UUID(), 'countries', 'Turkey', NULL, 12, TRUE),
  (UUID(), 'countries', 'South Africa', NULL, 13, TRUE),
  (UUID(), 'countries', 'United States', NULL, 14, TRUE),
  (UUID(), 'countries', 'Japan', NULL, 15, TRUE),
  (UUID(), 'provinces', 'Punjab', NULL, 1, TRUE),
  (UUID(), 'provinces', 'Sindh', NULL, 2, TRUE),
  (UUID(), 'provinces', 'Khyber Pakhtunkhwa', NULL, 3, TRUE),
  (UUID(), 'provinces', 'Balochistan', NULL, 4, TRUE),
  (UUID(), 'provinces', 'Gilgit-Baltistan', NULL, 5, TRUE),
  (UUID(), 'provinces', 'Islamabad Capital Territory', NULL, 6, TRUE),
  (UUID(), 'ports', 'Karachi Port', NULL, 1, TRUE),
  (UUID(), 'ports', 'Port Qasim', NULL, 2, TRUE),
  (UUID(), 'ports', 'Gwadar Port', NULL, 3, TRUE),
  (UUID(), 'ports', 'Lahore Dry Port', NULL, 4, TRUE),
  (UUID(), 'ports', 'Sialkot Dry Port', NULL, 5, TRUE),
  (UUID(), 'ports', 'Islamabad Dry Port', NULL, 6, TRUE),
  (UUID(), 'complaint_categories', 'Product quality issue', NULL, 1, TRUE),
  (UUID(), 'complaint_categories', 'SPS compliance issue', NULL, 2, TRUE),
  (UUID(), 'complaint_categories', 'Quantity discrepancy', NULL, 3, TRUE),
  (UUID(), 'complaint_categories', 'Packaging issue', NULL, 4, TRUE),
  (UUID(), 'complaint_categories', 'Documentation issue', NULL, 5, TRUE),
  (UUID(), 'complaint_categories', 'Shipment delay', NULL, 6, TRUE),
  (UUID(), 'complaint_categories', 'Payment dispute', NULL, 7, TRUE),
  (UUID(), 'complaint_categories', 'Misrepresentation', NULL, 8, TRUE),
  (UUID(), 'complaint_categories', 'Exporter conduct', NULL, 9, TRUE),
  (UUID(), 'complaint_categories', 'Inspection issue', NULL, 10, TRUE),
  (UUID(), 'complaint_categories', 'Regulatory issue', NULL, 11, TRUE),
  (UUID(), 'complaint_categories', 'Other', NULL, 12, TRUE),
  (UUID(), 'document_types', 'Buyer''s Quality Requirement Sheet', NULL, 1, TRUE),
  (UUID(), 'document_types', 'DDP SPS Certificate', NULL, 2, TRUE),
  (UUID(), 'document_types', 'Pre-Shipment Inspection (PSI) Report', NULL, 3, TRUE),
  (UUID(), 'document_types', 'Purchase Order / Export Contract', NULL, 4, TRUE),
  (UUID(), 'document_types', 'Commercial Invoice', NULL, 5, TRUE),
  (UUID(), 'document_types', 'Packing List', NULL, 6, TRUE),
  (UUID(), 'document_types', 'Certificate of Origin', NULL, 7, TRUE),
  (UUID(), 'document_types', 'Phytosanitary Certificate', NULL, 8, TRUE),
  (UUID(), 'document_types', 'Laboratory Test Report', NULL, 9, TRUE),
  (UUID(), 'document_types', 'Bill of Lading / Airway Bill', NULL, 10, TRUE),
  (UUID(), 'document_types', 'Additional Supporting Documents', NULL, 11, TRUE)
ON DUPLICATE KEY UPDATE
  code = VALUES(code),
  sort_order = VALUES(sort_order),
  is_active = TRUE;
